# yaml 配置
version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - database
    environment:
      - DATABASE_USER:${DB_USER}
      - DATABASE_PASSWORD:${DB_PASSWORD}
  redis:
    image: "redis:alpine"
  database:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER:${DB_USER}
      - POSTGRES_PASSWORD:${DB_PASSWORD}